apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: production-core-loop-14-19
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: core-loop-14-19
    name: production
  project: production
  source:
    chart: core-loop
    repoURL: https://chartmuseum.crunchbase.io/
    targetRevision: 1.101.11
    helm:
      valueFiles:
        - values-production.yaml
      values: |-
        global:
          environment: production
          rbac: true
          datadog_enabled: true
          dataid: "14"
          runid: "19"
        cardservice:
          export:
            replicas: 0
          postgres:
            export:
              host: cardservice-postgres.prod.crunchbase
            sink:
              host: pg-setl-{{ .Values.global.dataid }}-rw.prod.crunchbase
        entityservice:
          postgres:
            host: pg-entityservice13-rw.prod.crunchbase
            url:  jdbc:postgresql://pg-entityservice13-rw.prod.crunchbase:5432/entityservice?ApplicationName=entityservice
        streamingetl:
          metadataservice:
            postgres:
              host: metadataservice-postgres.prod.crunchbase
              url: jdbc:postgresql://metadataservice-postgres.prod.crunchbase/metadataservice?ApplicationName=metadataservice
          debezium:
            database:
              host: pg-entityservice13-rw.prod.crunchbase
          postgres:
            entityservice:
              host: pg-entityservice13-rw.prod.crunchbase
            listservice:
              host: pg-listservice13-rw.prod.crunchbase
            sink:
              host: pg-setl-{{ .Values.global.dataid }}-rw.prod.crunchbase
            streaming:
              host: pg-entityservice13-rw.prod.crunchbase
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        app.kubernetes.io/instance: production-core-loop-14-19
      annotations:
        argocd.argoproj.io/tracking-id: >-
          production-core-loop-14-19:/Namespace:core-loop-14-19/core-loop-14-19
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true # When syncing changes, respect fields ignored by the ignoreDifferences configuration

  # Will ignore differences between live and desired states during the diff. Note that these configurations are not
  # used during the sync process unless the `RespectIgnoreDifferences=true` sync option is enabled.
  ignoreDifferences:
    # for the specified json pointers
    - kind: CronJob
      jsonPointers:
      - /spec/suspend
    - kind: CronJob
      jsonPointers:
      - /spec/suspend
    - kind: Deployment
      name: worlddatadog-active
      jsonPointers:
      - /spec/replicas
    - kind: Deployment
      name: worlddatadog-pre
      jsonPointers:
      - /spec/replicas
    - kind: Deployment
      name: cardserviceexport
      jsonPointers:
      - /spec/replicas
    - kind: Deployment
      name: entityserviceconsumer
      jsonPointers:
      - /spec/replicas
    - kind: Job
      jsonPointers:
      - /spec/template/metadata/labels
