name: Promote Core Loop

permissions:
  id-token: write
  contents: write
  pull-requests: write

on:
  workflow_dispatch:
    inputs:
      staging_data_id:
        description: 'The Data ID for the staging cluster'
        required: false
        default: '1113'
        type: string
      staging_run_id:
        description: 'The unique Run ID for the staging cluster'
        required: true
        type: string
      production_data_id:
        description: 'The Data ID for the production cluster'
        required: false
        default: '14'
        type: string
      production_run_id:
        description: 'The unique Run ID for the production cluster'
        required: true
        type: string

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: validate input
        run: |-
          NUMBER_REGIX="^[0-9]+$"
          if [[ ! "${{ inputs.staging_data_id }}" =~ $NUMBER_REGIX ]]; then
            echo "Invalid staging Data ID format. Please specify a number."
            exit 1
          fi
          if [[ ! "${{ inputs.staging_run_id }}" =~ $NUMBER_REGIX ]]; then
            echo "Invalid staging Run ID format. Please specify a number."
            exit 1
          fi
          if [[ ! "${{ inputs.production_data_id }}" =~ $NUMBER_REGIX ]]; then
            echo "Invalid production Data ID format. Please specify a number."
            exit 1
          fi
          if [[ ! "${{ inputs.production_data_id }}" =~ $NUMBER_REGIX ]]; then
            echo "Invalid production Run ID format. Please specify a number."
            exit 1
          fi
      - name: create pull request
        id: pr
        run: |-
          demoted_prod=$(sed -n  's/.*\(core-loop-[0-9]\+-[0-9]\+\).*/\1/p' ./infrastructure/production/gateway.yaml | head -1)
          echo "demoted_prod=${demoted_prod}" >> $GITHUB_OUTPUT
          promoted_prod=core-loop-$(echo "${{ inputs.production_data_id }}")-$(echo "${{ inputs.production_run_id }}")
          echo "promoted_prod=${promoted_prod}" >> $GITHUB_OUTPUT
          demoted_stage=$(sed -n  's/.*\(core-loop-[0-9]\+-[0-9]\+\).*/\1/p' ./infrastructure/staging/gateway.yaml | head -1)
          echo "demoted_stage=${demoted_stage}" >> $GITHUB_OUTPUT
          promoted_stage=core-loop-$(echo "${{ inputs.staging_data_id }}")-$(echo "${{ inputs.staging_run_id }}")
          echo "promoted_stage=${promoted_stage}" >> $GITHUB_OUTPUT

          sed -e "s/core-loop-[0-9]\{1,\}-[0-9]\{1,\}/$promoted_prod/g" ./infrastructure/production/gateway.yaml
          sed -e "s/core-loop-[0-9]\{1,\}-[0-9]\{1,\}/$promoted_stage/g" ./infrastructure/staging/gateway.yaml

      - name: Extract run number
        shell: bash
        run: echo "number=${GITHUB_RUN_NUMBER}" >> $GITHUB_OUTPUT
        id: extract_run_number

      - name: create PR
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: Promote Core Loop
          title: "CB-00000: Bump core-loop in gateway"
          body: |
            This PR contains the following updates:
            | Environment | Change |
            |---|---|
            | production | `${{ steps.pr.outputs.demoted_prod }}` -> `${{ steps.pr.outputs.promoted_prod }}` |
            | staging    | `${{ steps.pr.outputs.demoted_stage }}` -> `${{ steps.pr.outputs.promoted_stage }}` |

            Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          branch: promote-${{ steps.extract_run_number.outputs.number }}
          labels: automated pr
